#import "@local/rpi-style:0.0.1": * 

#import "../../globalvars.typ": *

#show: rpi_whitepaper.with(
    title: "Changing the MAC Address on Raspberry Pi Single-Board Computers",
    version_string: [Version 1.7],
    version_history: (
    [1.0], [14 April 2021], [Initial release],
    [1.1], [16 June 2021], [Update for software-level setting],
    [1.2], [1 December 2021], [Update for bootloader-based MAC changes],
    [1.3], [27 April 2022], [Copy edit, public release],
    [1.4], [2 November 2022], [Update the OUI list, and provide a link to IEEE OUI database],
    [1.5], [3 November 2022], [Add information on the new MAC address from OTP feature],
    [1.6], [3 December 2023], [Add information on Pi 5],
    [1.7], [29 August 2024], [Update the OUI list],
    ), 
    platforms: ("AllSBC", "AllCM", "Pi400", "Pi500")
)

= Introduction

This white paper describes how to set a specific media access control (MAC) address on your #pi-prefix device. It applies to Ethernet, wireless, and Bluetooth interfaces.

Three mechanisms are described: one for devices up to Raspberry Pi 3, one for Raspberry Pi 4/400 and Compute Module 4, and one for #pi-prefix 5.

This whitepaper assumes that the #pi-prefix is running the #pi-prefix operating system (OS), and is fully up to date with the latest firmware and kernels.

= Techniques

== How are MAC addresses generated?

You can display the current MAC address for any #pi-prefix device using

```
$ ip link
```

or, for a specific device (e.g. `eth0`), using

```
$ ip link show eth0
```

The MAC address is the set of six hexadecimal numbers in the form aa:bb:cc:dd:ee:ff.

On devices prior to #pi-prefix 4 and 400, the MAC address is generated from the #pi-prefix board's serial number. For example, if your #pi-prefix serial number is 58d2ec5c, the MAC address will be generated from the bottom six nibbles, combined with the #pi-prefix Foundation Organizationally Unique Identifier (OUI), which is b8:27:eb, so the final MAC address would be b8:27:eb:d2:ec:5c.

This address is generated on startup by the firmware, and passed on to the Linux kernel for use by the Ethernet driver.

On #pi-prefix 4 and 400 with the 2711 SoC, the MAC address is generated by combining a #trading OUI (dc:a6:32 or e4:5f:01) with a final three bytes that are generated at production time from a sequential set; for example, dc:a6:32:c4:7c:5f.

This MAC address is stored in the one-time programmable (OTP) memory of the SoC and cannot be permanently changed, but can be overridden in software as described in a later section.

On #pi-prefix 5 and CM5 with the 2712 SoC, the MAC address is generated by combining a #trading OUI  with a final three bytes that are retrieved at production time from a database.


=== #trading OUIs

#pi-prefix MAC addresses are currently allocated from six OUI ranges, although new ranges will be added as each existing one is used up. Each range provides 0xffffff (six nibbles, 16777216 decimal) different IDs.

#table(
    columns: 2,
    table.header([OUI], [Owner]),
    [DC:A6:32], [#trading],
    [D8:3A:DD], [#trading],
    [E4:5F:01], [#trading],
    [28:CD:C1], [#trading],
    [2C:CF:67], [#trading],
    [B8:27:EB], [#pi-prefix Foundation],
)


For an up-to-date list of all #trading OUIs, please see the IEEE website at #link("https://regauth.standards.ieee.org/standards-ra-web/pub/view.html#registries")

== Setting a new MAC address from the command line

You can temporarily change the MAC address of the Ethernet adapter with the `ip` command:

```
$ sudo ip link set eth0 down
$ sudo ip link set eth0 address aa:bb:cc:dd:ee:ff
$ sudo ip link set eth0 up
```

The same process also applies to the wireless networking MAC address:

```
$ sudo ip link set wlan0 down
$ sudo ip link set wlan0 address aa:bb:cc:dd:ee:ff
$ sudo ip link set wlan0 up
```

#note[These commands are _not_ persistent over a reboot, so they will need to be re-entered each time or added to a login script to make this automatic.]


== Setting a persistent alternative MAC address on devices using SoCs prior to 2711 (#pi-prefix 1&#8211;3)

On Raspberry Pi 1 & 3 there is an area in the OTP memory that can be set to the new MAC address; if present, this address will be used instead of the address based on the serial number.

Programming the OTP requires using the `SET_MAC_ADDRESS_OTP` mailbox call (ID: 0x00030051). A utility is provided on all #pios installations for making mailbox calls to the firmware. The mailbox system accepts data in 32-bit words in little-endian format, so to set a MAC address of aa:bb:cc:dd:ee:ff you will need to do the following:

```
vcmailbox 0x00030051 6 6 0xddccbbaa 0x0000ffee
```

The two '6' parameters are the length, in bytes, of the question and response buffers.

Note that this operation is irreversible: once an OTP bit has moved from 0 to 1 it can never be set back to 0, so please be careful when using this command.

== Setting a persistent alternative MAC address on devices using the 2711 SoC (#pi-prefix 4 and 400, CM4)

On the 2711 SoC, a Raspberry Pi OUI-based MAC address is already stored in the OTP memory during production, and this particular entry cannot be changed. However, there are two options to override the preprogrammed MAC address, now available in all boot modes.

=== Changing MAC address via the bootloader

The boot EEPROM configuration on these devices has a setting to update the MAC address:

`MAC_ADDRESS=aa:bb:cc:dd:ee:ff`

To edit the EEPROM configuration, use the following command:

```
$ sudo -E rpi-eeprom-config --edit
```

Add the required `MAC_ADDRESS`, save, and reboot. The device should now use that MAC address when booting.

=== Changing MAC address using customer OTP (Pi 4)

In bootloader firmware dated November 2022 onwards, there is a feature to allow the use of a MAC address programmed into the customer OTP. By adding an OTP entry and then setting a bootloader flag, the bootloader will override the #pi-prefix MAC address from the OTP with the customer-specific version. The advantage of this over the previous mechanism is that the OTP cannot be reprogrammed to change the MAC address and only one EEPROM configuration image is necessary.

A MAC address requires two rows of customer OTP. The `Customer OTP` rows are OTP registers 36 to 43 in the `vcgencmd otp_dump` output; a document available in the #trading #link("https://pip.raspberrypi.com")[Product Information Portal] covers using the OTP.

The rows that the bootloader uses for the MAC address are specified by the bootloader flag `MAC_ADDRESS_OTP`. For example, to set to rows 0 and 1:

`MAC_ADDRESS_OTP=0,1`

To edit the EEPROM configuration, use the following command:

```
$ sudo -E rpi-eeprom-config --edit
```

Add the required `MAC_ADDRESS_OTP` entry, save, and reboot.

The first value (row 0 in the example) contains the OUI and the most significant eight bits of the MAC address. The second value (row 1 in the example) stores the remaining 16 bits of the MAC address. This is the same as the format used for the #pi-prefix MAC address programmed at manufacture.

== Setting a persistent alternative MAC address on devices using the 2712 SoC (#pi-prefix 5)

The scheme used on #pi-prefix 5 is an improvement on that used on #pi-prefix 4. It allows you to set the MAC addresses of the Ethernet, wireless, and Bluetooth systems, which is possible as the BCM2712 SoC has an enlarged OTP area to store this extra information. The mechanism for programming in these values is similar to that on #pi-prefix 4, and uses the `vcmailbox` system.

In the following sections, the MAC address to set is defined as follows; replace 'x' in the examples provided with '2', '3', or '4' according to the system for which you wish to set the MAC address:

#table(
    columns: 2, 
    table.header([x], [Device]),
    [2], [Ethernet],
    [3], [Wireless],
    [4], [Bluetooth],
)

=== Getting the customer MAC address

```
$ vcmailbox 0x0003008x 6 6 0 0
```

e.g. To get the wireless MAC address:

```
$ vcmailbox 0x00030083 6 6 0 0
0x00000020 0x80000000 0x00030083 0x00000006 0x80000006 0xddccbbaa 0x0000ffee 0x00000000
```

=== Setting the customer MAC address

The MAC address must be sent as two 32-bit words with the bytes in the right order. You can then set the customer MAC with the following command:

```
$ vcmailbox 0x0003808x 6 6 <row1> <row0>
```

e.g. To set a MAC address of 11:22:33:44:55:66 on the Ethernet port:

```
$ vcmailbox 0x00038082 6 6 0x44332211 0x6655
```

If a customer MAC address is set to ff:ff:ff:ff:ff:ff in the OTP, then it is ignored. This means that if a mistake is made when setting the OTP, you can set this value and the device will revert to the factory-set MAC address. Due to the write-once nature of the OTP, you would no longer be able to set a customer MAC address on the device.

A multicast address is NOT considered valid. The least significant bit in the most significant octet of a MAC address is the multicast bit, so make sure this is NOT set.

== Possible schemes for programming the MAC address on a #pi-prefix 4 or 5 device during production

There are any number of mechanisms for getting customer-specific MAC addresses onto a #pi-prefix 4 or 5 device on a production line. Here are some suggestions that may give some idea of the options available.

In the vast majority of cases, each device will require a unique MAC address to be assigned, so an image with a predefined MAC address is inappropriate. There is therefore a need for schemes to provide a unique address after an image has been installed. #pi-prefix 4 devices are assigned unique MAC addresses during production, but these include a #trading OUI.

One possible algorithm that should give almost non-repeating numbers could be to take the entire MAC address and replace the #trading OUI segment (the first three bytes) with a manufacturer-specific OUI, leaving the last three bytes as programmed. However, because of the large number of #pi-prefix 4 devices that have been made, there are multiple OUI ranges, so simply replacing the last three bytes could result in duplicate values. One option here is to use multiple customer OUI ranges to replace the multiple OUI ranges allocated to #trading.

An alternative scheme could be to use an external system to generate unique MAC addresses. The programmed image could be designed, on the first boot, to read from a MAC address provider via a script, which subsequently sets up the system to use the provided MAC address. The initial boot could be part of a provisioning/testing process on the production line; a server could provide unique numbers on request, and connect to a backend database for further provisioning information.